#!/bin/sh

set -eu

# XXX may be removed when merged
patch_remove_exams() {
  if ! grep -q '// KTPAPI REMOVE EXAMS' /var/lib/ktpjs/server/routes/import-exam-bl.js; then
    sed -i '
      /if (mebFileList.length === 0) {/a\
    using(pgrm.getTransaction(), async tx => { clearDatabase(tx).tap(clearFiles) }) // KTPAPI REMOVE EXAMS
' /var/lib/ktpjs/server/routes/import-exam-bl.js
  fi
}

case "$1" in
  configure)
    patch_remove_exams
    ;;
esac

#DEBHELPER#

exit 0
